apiVersion: serving.kserve.io/v1beta1
kind: InferenceService
metadata:
  name: wine-classifier
  namespace: models
  annotations:
    autoscaling.knative.dev/target: "20"
spec:
  predictor:
    serviceAccountName: model-puller
    minReplicas: 1
    maxReplicas: 5
    model:
      modelFormat:
        name: sklearn
      protocolVersion: v2
      runtime: kserve-sklearnserver
      storageUri: s3://kserve-models-123456789012-us-east-1/wine-classifier/v1
      resources:
        requests:
          cpu: 250m
          memory: 512Mi
        limits:
          memory: 1Gi
