$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: sklearn-train
version: "1"
image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04:latest
conda_file: conda.yaml
description: scikit-learn training environment with MLflow tracking
