apiVersion: v1
kind: Service
metadata:
  name: llm
  namespace: inference
  labels:
    app.kubernetes.io/name: llm
spec:
  selector:
    app.kubernetes.io/name: llm
  ports:
    - name: http
      port: 8000
      targetPort: http
