apiVersion: v1
kind: Service
metadata:
  name: gpu-inference
  labels:
    app.kubernetes.io/name: gpu-inference
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: gpu-inference
  ports:
    - name: http
      port: 8000
      targetPort: http
      protocol: TCP
