apiVersion: v1
kind: ConfigMap
metadata:
  name: mlflow-config
  namespace: mlflow
data:
  DB_HOST: REPLACED_BY_OVERLAY
  DB_PORT: "5432"
  DB_NAME: mlflow
  DB_SECRET_ARN: REPLACED_BY_OVERLAY
  ARTIFACT_BUCKET: REPLACED_BY_OVERLAY
  ARTIFACT_PREFIX: artifacts
  WORKERS: "2"
